[package]
name = "gower-rust"
version = "0.1.0"
authors = ["Harry Julian <harry.julian@peak.ai>"]

[lib]
name = "gower-rust"
crate-type = ["dylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
numpy = "0.17"
